# Generated by Django 5.0.3 on 2024-05-08 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artesano',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_y_apellido', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosTecnicos',
            fields=[
                ('Codigo_de_Datos_Tecnicos', models.AutoField(primary_key=True, serialize=False)),
                ('Procedencia', models.CharField(max_length=200)),
                ('Cultura', models.CharField(max_length=200)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Propetario_Original', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoConservacion',
            fields=[
                ('Codigo_de_Estado_de_Conservacion', models.AutoField(primary_key=True, serialize=False)),
                ('Condicion', models.CharField(max_length=200)),
                ('Integridad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('Cod_prestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha_prestamo', models.DateField()),
                ('Fecha_entrega', models.DateField()),
                ('Confirmacion', models.CharField(max_length=2)),
                ('Observacion_general', models.CharField(blank=True, max_length=45, null=True)),
                ('Fecha_devolucion', models.DateField(blank=True, null=True)),
                ('Estatus', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Prestatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('Codigo_de_Referencia', models.AutoField(primary_key=True, serialize=False)),
                ('Exposiciones', models.CharField(max_length=200)),
                ('Tratamiento', models.CharField(max_length=200)),
                ('Ubicacion_Deposito', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identidad', models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO'), ('P', 'RIF PERSONAL'), ('J', 'RIF JURIDICO')], default='V', max_length=1)),
                ('numero_identidad', models.CharField(default='0000000000', max_length=10, unique=True)),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Piezas',
            fields=[
                ('Cod_pieza', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Nombre_pieza', models.CharField(default='valor_predeterminado', max_length=45)),
                ('Composicion_pieza', models.CharField(default='valor_predeterminado', max_length=45)),
                ('Dimension_pieza', models.CharField(default='valor_predeterminado', max_length=45)),
                ('Soporte_tecnico_pieza', models.CharField(default='valor_predeterminado', max_length=45)),
                ('Fecha_pieza', models.DateField()),
                ('Marca_registro_pieza', models.CharField(default='valor_predeterminado', max_length=45)),
                ('Cod_artesano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.artesano')),
                ('Datos_Tecnicos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.datostecnicos')),
                ('Estado_de_Conservacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.estadoconservacion')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Referencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.referencias')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='piezas/')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='articulo.piezas')),
            ],
        ),
        migrations.CreateModel(
            name='Donante_pieza',
            fields=[
                ('Cod_ced_rif', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha_Donacion_Hora', models.DateTimeField()),
                ('Cod_pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.piezas')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('Cod_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Direccion', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=45)),
                ('Fecha_solicitud_prestamo', models.DateField()),
                ('Prestamo_Cod_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.prestamo')),
                ('Prestatario_Cod_rif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.prestatario')),
            ],
        ),
    ]
