# Generated by Django 5.0.3 on 2024-05-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='Fecha_solicitud_prestamo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
