# Generated by Django 5.0.3 on 2024-05-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_alter_solicitud_fecha_solicitud_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezas',
            name='Datos_Tecnicos',
        ),
        migrations.RemoveField(
            model_name='piezas',
            name='Estado_de_Conservacion',
        ),
        migrations.RemoveField(
            model_name='piezas',
            name='Referencia',
        ),
    ]
